services:
  recp:
    build:
      context: .
    image: recp:0.1.0
    container_name: recp
    restart: unless-stopped
    networks:
      - misc
    env_file:
      - .env
    labels:
      - "type=app"
    command: [ "uv", "run", "/app/src/main.py" ]

networks:
  misc:
    name: misc
    driver: bridge
