services:
  emitter:
    build:
      context: .
    image: emitter:0.1.0
    container_name: emitter
    restart: unless-stopped
    networks:
      - ffa
    env_file:
      - .env
    labels:
      - "type=app"
    command: [ "uv", "run", "/app/src/main.py" ]

networks:
  ffa:
    external: true
